import { Playfair  } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const playfair = Playfair({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
      <div className="md:px-10">
        <Header />
        {children}
      </div>
      
      </body>
    </html>
  );
}
